/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Player } from './types.ts';

export const PLAYERS_DATABASE: Player[] = [
  {
    id: '1',
    name: '马龙',
    nameEn: 'Ma Long',
    aliases: ['龙队', '六边形战士', '帝王龙', 'malong'],
    sex: '男',
    association: '中国',
    birthYear: 1988,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 8, // 2016，2020奥运单打；2015，2017，2019世乒赛单打；2012，2015，2024世界杯单打
    outCircleLevel: 1,
    signature: '双圈大满贯/六边形战士',
    difficulty: '入门'
  },
  {
    id: '2',
    name: '樊振东',
    nameEn: 'Fan Zhendong',
    aliases: ['小胖', '东哥', '小樊', 'fanzhendong'],
    sex: '男',
    association: '中国',
    birthYear: 1997,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 7, // 2024年奥运单打金牌；2021，2023世乒单打；2016，2018，2019，2020世界杯单打
    outCircleLevel: 1,
    signature: '超级大满贯/暴力弧圈之王',
    difficulty: '入门'
  },
  {
    id: '3',
    name: '王楚钦',
    nameEn: 'Wang Chuqin',
    aliases: ['大头', '小头', 'wangchuqin'],
    sex: '男',
    association: '中国',
    birthYear: 2000,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 2, // 2025世乒单打；2026世界杯单打
    outCircleLevel: 1,
    signature: '世界第一/霸王拧拉',
    difficulty: '入门'
  },
  {
    id: '4',
    name: '许昕',
    nameEn: 'Xu Xin',
    aliases: ['人民艺术家', '大蟒', '黄金左手', 'xuxin'],
    sex: '男',
    association: '中国',
    birthYear: 1990,
    activeStatus: '现役',
    hand: '左手',
    grip: '直拍',
    playStyle: '直拍横打',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '斯帝卡',
    honorGold: 1, // 2013年世界杯单打金牌
    outCircleLevel: 1,
    signature: '黄金左手/人民艺术家',
    difficulty: '入门'
  },
  {
    id: '5',
    name: '张继科',
    nameEn: 'Zhang Jike',
    aliases: ['藏獒', '帝国绝凶虎', 'zhangjike'],
    sex: '男',
    association: '中国',
    birthYear: 1988,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 5, // 2012奥运单；2011，2013世乒单；2011，2014世界杯单
    outCircleLevel: 1,
    signature: '445天最快大满贯',
    difficulty: '入门'
  },
  {
    id: '6',
    name: '孙颖莎',
    nameEn: 'Sun Yingsha',
    aliases: ['莎莎', '暴力莎', '小豆包', 'sunyingsha'],
    sex: '女',
    association: '中国',
    birthYear: 2000,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 5, // 2023、2025世乒单打；2024、2025、2026世界杯单打
    outCircleLevel: 1,
    signature: '全满贯领军人物/暴力美学',
    difficulty: '入门'
  },
  {
    id: '7',
    name: '陈梦',
    nameEn: 'Chen Meng',
    aliases: ['大梦', '梦姐', 'chenmeng'],
    sex: '女',
    association: '中国',
    birthYear: 1994,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 3, // 2020，2024奥运单打；2020世界杯单打
    outCircleLevel: 1,
    signature: '两届奥运女单冠军得主',
    difficulty: '入门'
  },
  {
    id: '8',
    name: '王曼昱',
    nameEn: 'Wang Manyu',
    aliases: ['鳗鱼', 'wangmanyu'],
    sex: '女',
    association: '中国',
    birthYear: 1999,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 1, // 2021世单
    outCircleLevel: 1,
    signature: '反手撕天裂地/休斯敦女单封王',
    difficulty: '入门'
  },
  {
    id: '9',
    name: '王皓',
    nameEn: 'Wang Hao',
    aliases: ['皓月', '王皓教练', 'wanghao'],
    sex: '男',
    association: '中国',
    birthYear: 1983,
    activeStatus: '退役',
    hand: '右手',
    grip: '直拍',
    playStyle: '直拍横打',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 4, // 2009世乒单，2007，2008，2010世界杯单
    outCircleLevel: 2,
    signature: '直拍横拉集大成者/三亚王',
    difficulty: '进阶'
  },
  {
    id: '10',
    name: '马琳',
    nameEn: 'Ma Lin',
    aliases: ['马教', '拼命三郎', 'malin'],
    sex: '男',
    association: '中国',
    birthYear: 1980,
    activeStatus: '退役',
    hand: '右手',
    grip: '直拍',
    playStyle: '直拍单面结合横打',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '亚萨卡',
    honorGold: 5, // 2008北京奥女/男单；2000，2003，2004，2006世单杯
    outCircleLevel: 2,
    signature: '算计之王/四届世界杯单打王',
    difficulty: '进阶'
  },
  {
    id: '11',
    name: '刘国梁',
    nameEn: 'Liu Guoliang',
    aliases: ['不懂球的胖子', '刘总督', 'liuguoliang'],
    sex: '男',
    association: '中国',
    birthYear: 1976,
    activeStatus: '退役',
    hand: '右手',
    grip: '直拍',
    playStyle: '直拍快攻结合弧圈',
    forehandRubber: '正胶',
    backhandRubber: '反胶',
    bladeBrand: '亚萨卡',
    honorGold: 3, // 1996奥运单，1999世单，1996世界杯
    outCircleLevel: 1,
    signature: '直拍短颗正胶天王/大满贯得主',
    difficulty: '进阶'
  },
  {
    id: '12',
    name: '孔令辉',
    nameEn: 'Kong Linghui',
    aliases: ['乒乓王子', '孔哥', 'konglinghui'],
    sex: '男',
    association: '中国',
    birthYear: 1975,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 3, // 2000悉尼奥单，1995世单，1995世杯单
    outCircleLevel: 2,
    signature: '乒乓王子/两面弧圈探路人',
    difficulty: '进阶'
  },
  {
    id: '13',
    name: '丁宁',
    nameEn: 'Ding Ning',
    aliases: ['大宝贝', '下蹲发球', 'dingning'],
    sex: '女',
    association: '中国',
    birthYear: 1990,
    activeStatus: '退役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 7, // 2016奥运单；2011，2015，2017世单；2011，2014，2018世杯单
    outCircleLevel: 1,
    signature: '下蹲砍式发球/大满贯得主',
    difficulty: '入门'
  },
  {
    id: '14',
    name: '刘诗雯',
    nameEn: 'Liu Shiwen',
    aliases: ['小枣', '枣姐', 'liushiwen'],
    sex: '女',
    association: '中国',
    birthYear: 1991,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 6, // 2019布达佩斯世单；5次世界杯单打
    outCircleLevel: 1,
    signature: '世界杯五冠王/极速狂澜',
    difficulty: '入门'
  },
  {
    id: '15',
    name: '张怡宁',
    nameEn: 'Zhang Yining',
    aliases: ['大魔王', '冷面杀手', '老张', 'zhangyining'],
    sex: '女',
    association: '中国',
    birthYear: 1981,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 8, // 2004，2008奥运单；2005，2009世单；4次世杯单打
    outCircleLevel: 1,
    signature: '两局大满贯得主/铁壁防守',
    difficulty: '入门'
  },
  {
    id: '16',
    name: '王楠',
    nameEn: 'Wang Nan',
    aliases: ['楠姐', '乒坛一姐', 'wangnan'],
    sex: '女',
    association: '中国',
    birthYear: 1978,
    activeStatus: '退役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 8, // 2000奥运单；1999，2001，2003世单；4次世界杯
    outCircleLevel: 2,
    signature: '全满贯传奇/24个世界冠军',
    difficulty: '进阶'
  },
  {
    id: '17',
    name: '邓亚萍',
    nameEn: 'Deng Yaping',
    aliases: ['初代大魔王', '乒坛皇后', 'dengyaping'],
    sex: '女',
    association: '中国',
    birthYear: 1973,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '长胶',
    bladeBrand: '蝴蝶',
    honorGold: 6, // 1992，1996奥运单；1991，1995，1997世单；1次世杯单
    outCircleLevel: 1,
    signature: '初代大魔王/连获两届奥运女单冠军',
    difficulty: '入门'
  },
  {
    id: '18',
    name: '林诗栋',
    nameEn: 'Lin Shidong',
    aliases: ['小石头', '栋哥', 'linshidong'],
    sex: '男',
    association: '中国',
    birthYear: 2005,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '新一代反手猛兽/超强爆拧',
    difficulty: '入门'
  },
  {
    id: '19',
    name: '林高远',
    nameEn: 'Lin Gaoyuan',
    aliases: ['高远', '林妹妹', '冷球手', 'lingaoyuan'],
    sex: '男',
    association: '中国',
    birthYear: 1995,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '远剑',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '极速近台/精妙左手布局',
    difficulty: '进阶'
  },
  {
    id: '20',
    name: '梁靖崑',
    nameEn: 'Liang Jingkun',
    aliases: ['大胖', '大梁', '昆哥', 'liangjingkun'],
    sex: '男',
    association: '中国',
    birthYear: 1996,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '雷神',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '单兵作战单打重炮/暴力反手拉球',
    difficulty: '进阶'
  },
  {
    id: '21',
    name: '张本智和',
    nameEn: 'Tomokazu Harimoto',
    aliases: ['摩托', '咆哮帝', '张本', 'harimoto'],
    sex: '男',
    association: '日本',
    birthYear: 2003,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '近台极速/咆哮得分狂人',
    difficulty: '入门'
  },
  {
    id: '22',
    name: '早田希娜',
    nameEn: 'Hina Hayata',
    aliases: ['苹果姬', '早田', 'hayata'],
    sex: '女',
    association: '日本',
    birthYear: 2000,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '日本现役一姐/暴力正手拉弧圈',
    difficulty: '入门'
  },
  {
    id: '23',
    name: '伊藤美诚',
    nameEn: 'Mima Ito',
    aliases: ['大头美诚', '发球大师', 'itomima'],
    sex: '女',
    association: '日本',
    birthYear: 2000,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '生胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '反手半颗粒快击/千变发球',
    difficulty: '入门'
  },
  {
    id: '24',
    name: '莫雷高德',
    nameEn: 'Truls Möregårdh',
    aliases: ['小莫', '六角板', '瑞典魔术师', 'moregard'],
    sex: '男',
    association: '瑞典',
    birthYear: 2002,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '斯帝卡',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '六角形球板/鬼手滑板魔术师',
    difficulty: '入门'
  },
  {
    id: '25',
    name: '费利克斯·勒布伦',
    nameEn: 'Félix Lebrun',
    aliases: ['小勒布伦', '眼镜侠', '直拍天才', 'felix'],
    sex: '男',
    association: '法国',
    birthYear: 2006,
    activeStatus: '现役',
    hand: '右手',
    grip: '直拍',
    playStyle: '直拍横打',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '挺拔',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '法国神童/欧洲最后直拍之光',
    difficulty: '入门'
  },
  {
    id: '26',
    name: '亚历克斯·勒布伦',
    nameEn: 'Alexis Lebrun',
    aliases: ['大勒布伦', '神经刀', 'alexis'],
    sex: '男',
    association: '法国',
    birthYear: 2003,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '挺拔',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '砍式发球脑洞大开/球风狂野神经刀',
    difficulty: '进阶'
  },
  {
    id: '27',
    name: '林昀儒',
    nameEn: 'Lin Yun-ju',
    aliases: ['沉默杀手', '小林同学', 'linyunju'],
    sex: '男',
    association: '中国台北',
    birthYear: 2001,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '冷若冰霜/沉默杀手拧拉神功',
    difficulty: '入门'
  },
  {
    id: '28',
    name: '雨果·卡尔德拉诺',
    nameEn: 'Hugo Calderano',
    aliases: ['巴西猛兽', '雨果', 'hugo'],
    sex: '男',
    association: '巴西',
    birthYear: 1996,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '挺拔',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '美洲第一大力重炮/远台对拉',
    difficulty: '进阶'
  },
  {
    id: '29',
    name: '波尔',
    nameEn: 'Timo Boll',
    aliases: ['波叔', '长青树', '波尔男神', 'timoboll'],
    sex: '男',
    association: '德国',
    birthYear: 1981,
    activeStatus: '退役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 2, // 2002，2005世界杯单打冠军
    outCircleLevel: 1,
    signature: '德国战车/全满贯陪跑绅士',
    difficulty: '入门'
  },
  {
    id: '30',
    name: '奥恰洛夫',
    nameEn: 'Dmitrij Ovtcharov',
    aliases: ['奥恰', '三剑客', '发球潜水艇', 'ovtcharov'],
    sex: '男',
    association: '德国',
    birthYear: 1988,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '深蹲潜水艇反手发球之神',
    difficulty: '入门'
  },
  {
    id: '31',
    name: '平野美宇',
    nameEn: 'Miu Hirano',
    aliases: ['飓风平野', '平野', 'hiranomiu'],
    sex: '女',
    association: '日本',
    birthYear: 2000,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 1, // 2016单打世界杯冠军（最年轻冠军得主）
    outCircleLevel: 2,
    signature: '一剑封喉/极速近台重排暴力',
    difficulty: '进阶'
  },
  {
    id: '32',
    name: '门卡·巴特拉',
    nameEn: 'Manika Batra',
    aliases: ['巴特拉', '印度长胶一姐', 'batra'],
    sex: '女',
    association: '印度',
    birthYear: 1995,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '长胶',
    bladeBrand: '挺拔',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '长胶怪球流/神功反排倒板发力',
    difficulty: '进阶'
  },
  {
    id: '33',
    name: '倪夏莲',
    nameEn: 'Ni Xia-lian',
    aliases: ['快乐奶奶', '乒坛祖母', '卢森堡阿姨', 'nixialian'],
    sex: '女',
    association: '卢森堡',
    birthYear: 1963,
    activeStatus: '现役',
    hand: '左手',
    grip: '直拍',
    playStyle: '直拍快攻结合弧圈',
    forehandRubber: '长胶',
    backhandRubber: '反胶',
    bladeBrand: 'VICTAS',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '乒坛不老松/快乐转圈长胶打法',
    difficulty: '入门'
  },
  {
    id: '34',
    name: '瓦尔德内尔',
    nameEn: 'Jan-Ove Waldner',
    aliases: ['老瓦', '乒坛莫扎特', '游击队长', 'waldner'],
    sex: '男',
    association: '瑞典',
    birthYear: 1965,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '多尼克',
    honorGold: 4, // 1992奥运单打；1989、1997世乒单打；1990世界杯单打
    outCircleLevel: 1,
    signature: '游击队长/乒坛莫扎特第一代大满贯',
    difficulty: '入门'
  },
  {
    id: '35',
    name: '申裕斌',
    nameEn: 'Shin Yu-bin',
    aliases: ['小八宝', '嘟嘟', 'shinyubin'],
    sex: '女',
    association: '韩国',
    birthYear: 2004,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '韩国人气王/嘟嘟国民甜心',
    difficulty: '入门'
  },
  {
    id: '36',
    name: '朱世赫',
    nameEn: 'Joo Sae-hyuk',
    aliases: ['世界第一削球手', '太极削球', 'joosaehyuk'],
    sex: '男',
    association: '韩国',
    birthYear: 1980,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '削中反攻',
    forehandRubber: '反胶',
    backhandRubber: '长胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '削中反攻大师/巴黎世乒赛男单银牌',
    difficulty: '进阶'
  },
  {
    id: '37',
    name: '柳承敏',
    nameEn: 'Ryu Seung-min',
    aliases: ['老柳', '雅典单打猛兽', 'ryuseungmin'],
    sex: '男',
    association: '韩国',
    birthYear: 1982,
    activeStatus: '退役',
    hand: '右手',
    grip: '直拍',
    playStyle: '两面弧圈', // traditional Japanese penhold single side, classified as loop or attack-loop
    forehandRubber: '反胶',
    backhandRubber: '长胶', // Japanese single ply actually contains bare back, but let's label logically
    bladeBrand: '蝴蝶',
    honorGold: 1, // 2004奥运单打冠军
    outCircleLevel: 2,
    signature: '日直单面爆冲天王/雅典战神',
    difficulty: '进阶'
  },
  {
    id: '38',
    name: '阿鲁纳',
    nameEn: 'Quadri Aruna',
    aliases: ['非洲天王', '阿鲁纳', '大力神鞭', 'aruna'],
    sex: '男',
    association: '尼日利亚',
    birthYear: 1988,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '挺拔',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '非洲第一重炮/大力出奇迹鞭打流',
    difficulty: '进阶'
  },
  {
    id: '39',
    name: '平野早矢香',
    nameEn: 'Sayaka Hirano',
    aliases: ['早矢香', '高压打法', '平野姐姐'],
    sex: '女',
    association: '日本',
    birthYear: 1985,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '斯帝卡',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '强悍防守硬女/日队夺银元老',
    difficulty: '大师'
  },
  {
    id: '40',
    name: '石川佳纯',
    nameEn: 'Kasumi Ishikawa',
    aliases: ['纯妹', '佳纯酱', 'ishikawaycasumi'],
    sex: '女',
    association: '日本',
    birthYear: 1993,
    activeStatus: '退役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '中文满级少女/日本国民级女神',
    difficulty: '入门'
  },
  {
    id: '41',
    name: '福原爱',
    nameEn: 'Ai Fukuhara',
    aliases: ['爱酱', '瓷娃娃', '小爱', 'fukuhara'],
    sex: '女',
    association: '日本',
    birthYear: 1988,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '生胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '瓷娃娃/中日友好使者',
    difficulty: '入门'
  },
  {
    id: '42',
    name: '张本美和',
    nameEn: 'Miwa Harimoto',
    aliases: ['神奇美和', '美和', 'harimotomiwa'],
    sex: '女',
    association: '日本',
    birthYear: 2008,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '超低龄天才少女/张本智和亲妹妹',
    difficulty: '入门'
  },
  {
    id: '43',
    name: '户上隼辅',
    nameEn: 'Shunsuke Togami',
    aliases: ['户上', '暴躁反手', 'togami'],
    sex: '男',
    association: '日本',
    birthYear: 2001,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '两届全日男单冠军/暴力进攻流',
    difficulty: '进阶'
  },
  {
    id: '44',
    name: '田志希',
    nameEn: 'Jeon Ji-hee',
    aliases: ['田姐', '欧尼', '田大美', 'jeonjihee'],
    sex: '女',
    association: '韩国',
    birthYear: 1992,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '韩国一姐/幽默宠粉达人',
    difficulty: '进阶'
  },
  {
    id: '45',
    name: '郑怡静',
    nameEn: 'Cheng I-ching',
    aliases: ['怡静', '台北一姐', 'chengyiching'],
    sex: '女',
    association: '中国台北',
    birthYear: 1992,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '台北定海神针/硬朗派风采',
    difficulty: '进阶'
  },
  {
    id: '46',
    name: '庄智渊',
    nameEn: 'Chuang Chih-yuan',
    aliases: ['庄爸', '庄神', '台北长青树', 'chuang'],
    sex: '男',
    association: '中国台北',
    birthYear: 1981,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '单兵作战传奇/永不言败不屈斗士',
    difficulty: '进阶'
  },
  {
    id: '47',
    name: '法尔克',
    nameEn: 'Mattias Falck',
    aliases: ['大维法尔克', '法尔克', 'falck'],
    sex: '男',
    association: '瑞典',
    birthYear: 1991,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈', // uses short pips (正胶) on forehand and inverted on backhand
    forehandRubber: '正胶',
    backhandRubber: '反胶',
    bladeBrand: '亚萨卡',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '正手正贴短颗奇迹/休斯敦世乒银牌得主',
    difficulty: '大师'
  },
  {
    id: '48',
    name: '卡尔松',
    nameEn: 'Kristian Karlsson',
    aliases: ['卡尔松', '瑞典左手', 'karlsson'],
    sex: '男',
    association: '瑞典',
    birthYear: 1991,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '瑞典夺冠功勋/左手暴力撕抢',
    difficulty: '大师'
  },
  {
    id: '49',
    name: '邱党',
    nameEn: 'Dang Qiu',
    aliases: ['邱老师', '德国直拍', 'qiudang'],
    sex: '男',
    association: '德国',
    birthYear: 1996,
    activeStatus: '现役',
    hand: '右手',
    grip: '直拍',
    playStyle: '直拍横打',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '高知直拍学者/新晋德乒直拍骄傲',
    difficulty: '大师'
  },
  {
    id: '50',
    name: '弗朗西斯卡',
    nameEn: 'Patrick Franziska',
    aliases: ['弗神', '弗大炮', 'franziska'],
    sex: '男',
    association: '德国',
    birthYear: 1992,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '巨人身躯/大心脏克星战神',
    difficulty: '进阶'
  },
  {
    id: '51',
    name: '斯佐科斯',
    nameEn: 'Bernadette Szocs',
    aliases: ['斯佳丽', '罗马尼亚美女', '彩色皮王', 'szocs'],
    sex: '女',
    association: '罗马尼亚',
    birthYear: 1995,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '挺拔',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '粉红胶皮代言人/欧洲抗中美女排头兵',
    difficulty: '进阶'
  },
  {
    id: '52',
    name: '袁嘉楠',
    nameEn: 'Jia Nan Yuan',
    aliases: ['高抛女王', '高抛袁', 'yuanjianan'],
    sex: '女',
    association: '法国',
    birthYear: 1985,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈', // forehand positive short pip, backhand inverted
    forehandRubber: '正胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '直上云霄高抛发球/近台生正封阻',
    difficulty: '大师'
  },
  {
    id: '53',
    name: '张禹珍',
    nameEn: 'Jang Woo-jin',
    aliases: ['大圣', '疯狂奔跑者', 'jangwoojin'],
    sex: '男',
    association: '韩国',
    birthYear: 1995,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '疯狂正手爆发力/暴躁大圣',
    difficulty: '进阶'
  },
  {
    id: '54',
    name: '林钟勋',
    nameEn: 'Lim Jong-hoon',
    aliases: ['混双韩国一哥', '林队长', 'limjonghoon'],
    sex: '男',
    association: '韩国',
    birthYear: 1997,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '混双关键先生/反手撕弧圈球',
    difficulty: '进阶'
  },
  {
    id: '55',
    name: '郭跃',
    nameEn: 'Guo Yue',
    aliases: ['跃跃', '帅气郭跃', 'guoyue'],
    sex: '女',
    association: '中国',
    birthYear: 1988,
    activeStatus: '退役',
    hand: '左手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 1, // 2007世单
    outCircleLevel: 2,
    signature: '假小子/极其暴力的左手前三板',
    difficulty: '进阶'
  },
  {
    id: '56',
    name: '李晓霞',
    nameEn: 'Li Xiaoxia',
    aliases: ['李锤子', '霞姐', 'lixiaoxia'],
    sex: '女',
    association: '中国',
    birthYear: 1988,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 3, // 2012奥运单；2013世锦单；2008世杯单
    outCircleLevel: 2,
    signature: '李大锤/功勋盖世大满贯',
    difficulty: '进阶'
  },
  {
    id: '57',
    name: '王励勤',
    nameEn: 'Wang Liqin',
    aliases: ['大力', '励勤', 'wangliqin'],
    sex: '男',
    association: '中国',
    birthYear: 1978,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 3, // 2001，2005，2007世单金牌
    outCircleLevel: 2,
    signature: '正手力量之神/无解对拉肌肉群',
    difficulty: '进阶'
  },
  {
    id: '58',
    name: '李佳薇',
    nameEn: 'Li Jiawei',
    aliases: ['佳薇', '新加坡主力', 'lijiawei'],
    sex: '女',
    association: '新加坡',
    birthYear: 1981,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈', // backhand short pip生胶
    forehandRubber: '反胶',
    backhandRubber: '生胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '北京胡同走出的新加坡乒坛一姐',
    difficulty: '大师'
  },
  {
    id: '59',
    name: '弗拉基米尔·萨姆索诺夫',
    nameEn: 'Vladimir Samsonov',
    aliases: ['老萨', '乒坛绅士', '太极老萨', 'samsonov'],
    sex: '男',
    association: '白俄罗斯',
    birthYear: 1976,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '挺拔',
    honorGold: 3, // 三次单打世界杯冠军
    outCircleLevel: 2,
    signature: '乒坛太极绅士宗师/防守太极神功',
    difficulty: '进阶'
  },
  {
    id: '60',
    name: '金泽洙',
    nameEn: 'Kim Taek-soo',
    aliases: ['拼命三郎', '金教练', 'kimtaeksoo'],
    sex: '男',
    association: '韩国',
    birthYear: 1970,
    activeStatus: '退役',
    hand: '右手',
    grip: '直拍',
    playStyle: '两面弧圈', // traditional Single side Penhold loop
    forehandRubber: '反胶',
    backhandRubber: '长胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '日直单面搏杀拼命三郎',
    difficulty: '大师'
  },
  {
    id: '61',
    name: '杜凯琹',
    nameEn: 'Doo Hoi Kem',
    aliases: ['阿琹', '香港女一', 'dooholkem'],
    sex: '女',
    association: '中国香港',
    birthYear: 1996,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '香港一姐/东京混双摘铜核心',
    difficulty: '进阶'
  },
  {
    id: '62',
    name: '木原美悠',
    nameEn: 'Miyuu Kihara',
    aliases: ['木原', '颗粒快攻少女', 'kihara'],
    sex: '女',
    association: '日本',
    birthYear: 2004,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈', // backhand short pips (生胶)
    forehandRubber: '反胶',
    backhandRubber: '生胶',
    bladeBrand: 'VICTAS',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '双打大师/反手近台暴弹生胶',
    difficulty: '大师'
  },
  {
    id: '63',
    name: '徐孝元',
    nameEn: 'Suh Hyo-won',
    aliases: ['削球美女', '徐漂亮', 'suhhyowon'],
    sex: '女',
    association: '韩国',
    birthYear: 1987,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '削中反攻',
    forehandRubber: '反胶',
    backhandRubber: '长胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 1,
    signature: '颜值担当/坚若磐石的长胶大底削球',
    difficulty: '进阶'
  },
  {
    id: '64',
    name: '韩莹',
    nameEn: 'Han Ying',
    aliases: ['老韩', '德乒盾牌', 'hanying'],
    sex: '女',
    association: '德国',
    birthYear: 1983,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '削中反攻',
    forehandRubber: '反胶',
    backhandRubber: '短胶', // can be classified as short or long pips
    bladeBrand: 'VICTAS',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '欧洲第一坚盾/恐怖的防守耐磨度',
    difficulty: '大师'
  },
  {
    id: '65',
    name: '单晓娜',
    nameEn: 'Shan Xiaona',
    aliases: ['娜姐', '德国女直', 'shanxiaona'],
    sex: '女',
    association: '德国',
    birthYear: 1983,
    activeStatus: '现役',
    hand: '右手',
    grip: '直拍',
    playStyle: '快攻结合弧圈', // single sided short pip straight penhold fast attack
    forehandRubber: '正胶',
    backhandRubber: '长胶',
    bladeBrand: 'VICTAS',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '单面正胶传统快攻/欧洲最后的传统直拍',
    difficulty: '大师'
  },
  {
    id: '66',
    name: '向鹏',
    nameEn: 'Xiang Peng',
    aliases: ['小向鹏', '鹏哥', 'xiangpeng'],
    sex: '男',
    association: '中国',
    birthYear: 2003,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '力量出众/国乒潜力超新星',
    difficulty: '大师'
  },
  {
    id: '67',
    name: '安宰贤',
    nameEn: 'An Jae-hyun',
    aliases: ['世乒赛黑马', '安神', 'anjaehyun'],
    sex: '男',
    association: '韩国',
    birthYear: 1999,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '2019布达佩斯一鸣惊人夺铜大黑马',
    difficulty: '大师'
  },
  {
    id: '68',
    name: '斯里贾·阿库拉',
    nameEn: 'Sreeja Akula',
    aliases: ['阿库拉', '印度长胶二姐', 'akula'],
    sex: '女',
    association: '印度',
    birthYear: 1998,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '长胶',
    bladeBrand: 'VICTAS',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '反手长胶进攻打法/WTT击败主力新锐',
    difficulty: '大师'
  },
  {
    id: '69',
    name: '袁励岑',
    nameEn: 'Yuan Licen',
    aliases: ['小袁', '元力', 'yuanlicen'],
    sex: '男',
    association: '中国',
    birthYear: 2000,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '极速快攻反击/左手灵气搭档',
    difficulty: '全知'
  },
  {
    id: '70',
    name: '黄镇廷',
    nameEn: 'Wong Chun Ting',
    aliases: ['阿廷', '香港一哥', 'wongchunting'],
    sex: '男',
    association: '中国香港',
    birthYear: 1991,
    activeStatus: '现役',
    hand: '右手',
    grip: '直拍',
    playStyle: '直拍横打',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '香港直拍一哥/反手拧拉大成者',
    difficulty: '进阶'
  },
  {
    id: '71',
    name: '约奇克',
    nameEn: 'Darko Jorgic',
    aliases: ['暗黑骑士', '达科', 'jorgic'],
    sex: '男',
    association: '斯洛文尼亚',
    birthYear: 1998,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '挺拔',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '欧洲豪强/无解暴力大板反手撕',
    difficulty: '大师'
  },
  {
    id: '72',
    name: '赵大成',
    nameEn: 'Cho Dae-seong',
    aliases: ['赵大成', '韩国新星', 'chodaeseong'],
    sex: '男',
    association: '韩国',
    birthYear: 2002,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '左手横板双打奇才/冲击锋锐',
    difficulty: '全知'
  },
  {
    id: '73',
    name: '篠塚大登',
    nameEn: 'Hiroto Shinozuka',
    aliases: ['篠冢', '登登', 'shinozuka'],
    sex: '男',
    association: '日本',
    birthYear: 2003,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '左手轻盈飘逸近台撕控',
    difficulty: '全知'
  },
  {
    id: '74',
    name: '李尚洙',
    nameEn: 'Lee Sang-su',
    aliases: ['老李', '尚洙大叔', 'leesangsu'],
    sex: '男',
    association: '韩国',
    birthYear: 1990,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '近台搏杀猛将/遇强则强打疯了',
    difficulty: '进阶'
  },
  {
    id: '75',
    name: '朱雨玲',
    nameEn: 'Zhu Yuling',
    aliases: ['小朱', '小猪', 'zhuyuling'],
    sex: '女',
    association: '中国',
    birthYear: 1995,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 1, // 2017世界杯单打冠军
    outCircleLevel: 2,
    signature: '近台防守太极神功/世界杯单打冠军',
    difficulty: '进阶'
  },
  {
    id: '76',
    name: '冯天薇',
    nameEn: 'Feng Tianwei',
    aliases: ['天薇', '新加坡功勋一姐', 'fengtianwei'],
    sex: '女',
    association: '新加坡',
    birthYear: 1986,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '红双喜',
    honorGold: 0, // Got team golds, but olympic or world singles golds count: 0 (Got bronze, silver in singles)
    outCircleLevel: 2,
    signature: '带领新加坡夺得莫斯科世锦赛女团冠军',
    difficulty: '进阶'
  },
  {
    id: '77',
    name: '帖雅娜',
    nameEn: 'Tie Ya Na',
    aliases: ['雅娜', '帖姐', 'tieyana'],
    sex: '女',
    association: '中国香港',
    birthYear: 1979,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '香港昔日绝对主炮/沉稳防守撕斜线',
    difficulty: '大师'
  },
  {
    id: '78',
    name: '吉村真晴',
    nameEn: 'Maharu Yoshimura',
    aliases: ['真晴', '吉村', 'yoshimura'],
    sex: '男',
    association: '日本',
    birthYear: 1993,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '逆旋转发球之神/混双夺金元老',
    difficulty: '进阶'
  },
  {
    id: '79',
    name: '陈建安',
    nameEn: 'Chen Chien-an',
    aliases: ['陈建安', '台北核心', 'chenchienan'],
    sex: '男',
    association: '中国台北',
    birthYear: 1991,
    activeStatus: '现役',
    hand: '左手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 3,
    signature: '巴黎单打爆冷杀手/双打世锦赛夺冠功臣',
    difficulty: '大师'
  },
  {
    id: '80',
    name: '高承睿',
    nameEn: 'Kao Cheng-jui',
    aliases: ['柚子高', '庄门高徒', 'kaochengjui'],
    sex: '男',
    association: '中国台北',
    birthYear: 2004,
    activeStatus: '现役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 2,
    signature: '中近台极速衔接/庄智渊关门大弟子',
    difficulty: '进阶'
  },
  {
    id: '81',
    name: '佩尔森',
    nameEn: 'Jörgen Persson',
    aliases: ['老佩', 'Persson', '瑞典长青树', 'peiersen'],
    sex: '男',
    association: '瑞典',
    birthYear: 1966,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '斯帝卡',
    honorGold: 2, // 1991年世乒单，1991世界杯单打金牌
    outCircleLevel: 2,
    signature: '瑞典三驾马车之一/大局反手冷封',
    difficulty: '进阶'
  },
  {
    id: '82',
    name: '施拉格',
    nameEn: 'Werner Schlager',
    aliases: ['施拉格', '老施', 'schlager'],
    sex: '男',
    association: '奥地利',
    birthYear: 1972,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '两面弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '蝴蝶',
    honorGold: 1, // 2003年世锦赛单打金牌 (legendary scale!)
    outCircleLevel: 2,
    signature: '2003年巴黎世锦赛单打绝顶反差夺金传奇',
    difficulty: '大师'
  },
  {
    id: '83',
    name: '盖亭',
    nameEn: 'Jean-Philippe Gatien',
    aliases: ['法兰西火炮', '盖亭', 'gatien'],
    sex: '男',
    association: '法国',
    birthYear: 1968,
    activeStatus: '退役',
    hand: '左手',
    grip: '横拍',
    playStyle: '快攻结合弧圈',
    forehandRubber: '反胶',
    backhandRubber: '反胶',
    bladeBrand: '亚萨卡',
    honorGold: 2, // 1993世单, 1994世杯
    outCircleLevel: 3,
    signature: '法国队历史巨擘/全台极速高爆正手',
    difficulty: '大师'
  },
  {
    id: '84',
    name: '陈卫星',
    nameEn: 'Chen Weixing',
    aliases: ['陈老铁', '削球悍将', 'chenweixing'],
    sex: '男',
    association: '奥地利',
    birthYear: 1972,
    activeStatus: '退役',
    hand: '右手',
    grip: '横拍',
    playStyle: '削中反攻',
    forehandRubber: '反胶',
    backhandRubber: '长胶',
    bladeBrand: '蝴蝶',
    honorGold: 0,
    outCircleLevel: 4,
    signature: '削中突爆正手拉/奥地利主力削球高手',
    difficulty: '全知'
  }
];

/** 旧版球员数据库别名——供 dataMerger.ts 引用旧数据做补充字段 */
export const LEGACY_PLAYERS: Player[] = PLAYERS_DATABASE;
